swyp-9-web/indi-front

.github/workflows/deploy.yml

1. Vercel CLI를 이용한 배포 GitHub workflow 작성 (Preview 용도)
2. ⚠️ 주의 사항!
- PR을 등록한 이후 커밋을 여러 번 push할 경우, 커밋마다 Vercel 배포가 자동으로 실행됩니다.
- 이로 인해 배포 횟수 제한에 걸릴 수 있으니, 가능한 여러 개의 커밋이라도 push는 한번에 진행하시는걸 권장합니다.

chore(ci): Vercel CLI 배포 GitHub Action workflow 추가

---

.github/workflows/deploy.yml

- main 브랜치를 production 배포 중 발생하는 오류를 해결하기 위해 main 브랜치 build시에 --prod 옵션을 추가하여 배포 에러를 수정합니다.
[실제 Actions 오류 로그](https://github.com/swyp-9-web/indi-front/actions/runs/14429667725/job/40462916307)

fix(ci): Vercel production 환경 배포 오류 수정

---

app/_components/layout/FollowingDropdown.tsx
app/_components/layout/GlobalNavBar.tsx
app/_components/layout/UserProfileDropdown.tsx
constants/category-items.ts
constants/index.ts
constants/size-items.ts
lib/mocks/following-preview.mock.ts

1. mock 데이터 변경으로 인해 리팩토링 진행하였습니다.
2. 상수 `category-items`와 `size-items` 값을 수정 및 생성하였습니다.
- 백엔드 enum 값과 일치시켜야해서 전달받는대로 수정해서 사용하면 될 것 같습니다.

refactor(layout): 글로벌 네비게이션 바 리팩토링

---

components/ui/form.tsx
components/ui/label.tsx
package.json
pnpm-lock.yaml

1. shadcn/ui의 form과 label을 추가합니다.

chore(ui): shadcn/ui form 및 label 패키지 추가

---

.github/workflows/deploy-branch.yml
.github/workflows/deploy-preview-on-label.yml

1. main과 dev의 환경변수를 prod 기준으로 가져오게 변경했습니다.
2. 모든 배포 workflow의 환경변수를 가져오는 설정에 --dotenv를 추가하였습니다.

fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경

---

.github/workflows/deploy-branch.yml
.github/workflows/deploy-preview-on-label.yml

1. #35 의 배포 관련 명령어를 최신 버전을 반영하여 재수정 하였습니다.

fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경 (2차 수정)

---

.github/workflows/deploy-branch.yml
.github/workflows/deploy-preview-on-label.yml

Reverts swyp-9-web/indi-front#36

Revert "fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경 (2차 수정)"

---

.github/workflows/deploy-branch.yml
.github/workflows/deploy-preview-on-label.yml

Reverts swyp-9-web/indi-front#35

Revert "fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경"

---

app/(routes)/(main)/_components/DefaultProductsGrid.tsx
app/(routes)/artists/[id]/_components/ArtistInfoButtons.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection.tsx
app/(routes)/artists/[id]/_components/ArtistProductsGrid.tsx
app/(routes)/artists/[id]/page.tsx
app/_components/product/ProductCard.tsx
app/_components/product/ScrapButton.tsx
lib/apis/products.type.ts
lib/apis/user.api.ts
lib/apis/user.type.ts
utils/queryParams.ts

1. 작가 피드 페이지의 정보를 API와 연동하였습니다.
2. 팔로우 기능을 연동하였습니다.

feat(artist): 작가 피드 페이지 API 연동

---

app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection/EditProfileForm.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
lib/queries/useUserQueries.ts

1. 작가 피드 페이지 링크 공유 버튼에 누락된 기능을 추가하였습니다.
2. 이미지 파일 유효성 검사를 추가하였습니다.
3. 로그아웃 시 작가 프로필을 수정할 수 있던 현상을 수정하였습니다.

fix(artist): 작가 피드 페이지 버그 수정 및 공유 기능 추가

---

next.config.ts

1. 오류 발생으로 인해 remote patterns를 좀 더 구체적으로 정의해주었습니다.

fix(next): Next 이미지 remote patterns 수정

---

app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
app/_components/product/HighlightedProductsCarousel.tsx

1. 미 구현 기능에 대한 안내 toast를 추가하였습니다. ("아직 준비 중인 기능입니다")
2. 메인 페이지 HighlightedProductsCarousel의 기본 높이를 지정하고, 상품이 4개 이하인 경우 navgiation 버튼을 렌더링 하지 않도록 수정하였습니다.

feat(ui): 메인 페이지 UI 변경사항 반영 및 미구현 기능 안내 toast 추가

---

app/(routes)/products/[id]/_components/ProductDetailGallery.tsx

- key 를 수정해서 같은 이름의 여러이미지를 올려도 가능하게 만들었습니다
- cn 추가 했습니다

fix(detail): 이미지 갤러리-여러 이미지 올릴시에 에러 해결

---

app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection/EditProfileForm.tsx
app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
app/(routes)/artists/products/register/_components/ImageUploadInput.tsx
app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
app/(routes)/artists/products/register/_components/SizeInputGroup.tsx
app/(routes)/mypage/(mypage)/_components/UserProfilePanel/ProfileEditForm.tsx
app/(routes)/mypage/(mypage)/_components/UserProfilePanel/index.tsx
app/(routes)/mypage/following/_components/FollowingArtistRow.tsx
app/(routes)/products/category/[category_value]/page.tsx
app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
app/_components/product/ProductCard.tsx
lib/schemas/artistProfileEditForm.schema.ts
lib/schemas/productRegisterForm.schema.ts

1. 스타일 변경
- 작가 피드 페이지 작품 등록 버튼 cursor pointer로 변경
- 작품 수정하기 페이지에서 취소 버튼 추가
2. 기능 추가
- ProductCard 디자인 수정 및 이미지 클릭 시 상세 페이지로 이동 추가
- 팔로잉 페이지 작가 닉네임 클릭 시 해당 작가 피드 페이지로 이동
- 작품 등록/수정 페이지 이미지 유효성 검사 추가 및 size, price 유효성 검사 기능 추가
3. 리팩토링
- 작품 등록/수정 시 중복 API 요청 방지 (disabled)
- 작가 피드 페이지 링크 중복 렌더링 허용 (key 값 변경)
- 작가 및 유저 프로필 수정 폼의 문자열 길이 제한 기준을 공백 포함으로 수정

fix(qa): 1차 테스트 QA UI 수정 반영 및 interaction 변경

---

app/_components/layout/GlobalNavBar.tsx
app/_components/layout/HeaderLeftSection/CategoryDropdown.tsx
app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
app/_components/layout/HeaderRightSection/NotificationPopover.tsx
app/_components/layout/HeaderRightSection/UserProfileDropdown.tsx
app/_components/product/ProductCard.tsx
app/layout.tsx

1. GlobalNavBar의 position 값을 sticky로 변경하였습니다.
2. Dropdown 및 popover의 position을 props를 통해 설정하도록 수정하였습니다.

fix(layout): 네비게이션 바 dropdown, popover 위치 수정 및 sticky로 변경

---

app/(routes)/products/[id]/_components/CommentCount.tsx
app/(routes)/products/[id]/_components/PatchAndDelete.tsx
app/(routes)/products/[id]/page.tsx

- 회원 탈퇴 모달 추가
- 댓글 카운트 반영
- api 호출 부분 리팩토링

feat(detail):  제품상세페이지 UI 수정 및 리팩토링

---

app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx

1. 작가 피드 페이지 링크 렌더 조건 miss로 인한 렌더링 이슈를 수정하였습니다.

fix(artist): 작가 피드 페이지 웹사이트 링크 렌더 오류 수정

---

app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx

1. 코드 디버깅에 사용했던 불필요한 console.log를 제거했습니다.

refactor(artist): 불필요한 console.log 제거

---

app/(routes)/products/[id]/_components/CommentCount.tsx
app/(routes)/products/[id]/_components/PatchAndDelete.tsx
app/(routes)/products/[id]/_components/ProductDetailAuthorInfo.tsx
app/(routes)/products/[id]/_components/ProductDetailGallery.tsx
app/(routes)/products/[id]/_components/ScrapAndShare.tsx
app/(routes)/products/[id]/page.tsx

- 999이하여도 + 되는 부분 제거
- 수정,삭제 로직이 제대로 작동안해서 수정했습니다.
- 이미지 퀄리티를 개선했습니다
- 에러가 발생하면 404페이지로 이동

fix(Detail): 작품상세페이지 UI 수정 및 리다이렉팅

---

hooks/useFollowToggle.ts

1. `useFollowToggle` 커스텀 훅에 count 값을 낙관적 업데이트 하도록 변경하였습니다.
- 사용 방법에는 변경사항이 없습니다~

feat(hooks): useFollowToggle 팔로잉 count 값 낙관적 업데이트 반영

---

app/layout.tsx
package.json
pnpm-lock.yaml

1. 배포 사이트 속도 테스트를 위한 Verccel SpeenInsights를 추가하였습니다.

feat(test): vercel speed insights 추가

---

app/(routes)/admin/_components/AllowAndDisallow.tsx
app/(routes)/admin/_components/ArtistRow.tsx
app/(routes)/admin/_components/ArtistsList.tsx
app/(routes)/admin/_components/Status.tsx
app/(routes)/admin/_components/ViewDetails.tsx
app/(routes)/admin/page.tsx
app/(routes)/products/[id]/_components/PatchAndDelete.tsx
hooks/useArtistApplies.ts
lib/apis/admin.api.ts
lib/apis/admin.type.ts
lib/apis/user.type.ts

- 백오피스 페이지 생성
- 작가승인,반려,조회 api 생성
- 작가승인,반려,조회 타입 생성

feat(backoffice): 백오피스 페이지 구현

---

app/(routes)/products/[id]/_components/ProductDetailGallery.tsx

- lazyloading 추가했습니다
- 이미지 로딩속도가 5s -> 2.2s 로 단축 되었습니다.

refactor(datail): 이미지 최적화
